### ISSUE TITLE
Details of BSS parallelisation options / schemes

### ISSUE THREAD

**Issue by DreamCykl** [OpenBioSim/biosimspace#102]
Hi,

I'm looking at running BSS.FreeEnergy.Relative calculations. I would like to have a better understanding of how this process uses multiple cores and GPus, running either via SOMD or GROMACS engine. 

For example, if I wish to calculate RBFE differences between a set of 10 mols, I would like to know whether I would see large benefits in optimising the process beyond running mol_a, mol_b edges in serial using .run() methods. Or, does BSS automatically scale single simulations to use the maximum compute, and thus trying to run edges in parallel would be pointless?

There are multiple compute scenarios in which I wish to run these calculations.

1) Using my workstation which is an 8 core system with a consumer RTX GPU. 
2) Using a larger compute node/VM with 64 vCPUs and 4 GPUs. 
3) In the future, I may perform these simulations using a cloud system where I can spawn VMs when necessary. 

I have looked at the documentation but haven't been able to find much information.

Thanks

**Comment by jmichel80** [comment]
hi @DreamCykl 

This [notebook](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/01_intro_to_alchemy/alchemical_introduction.ipynb) highlights how to run a simple RBFE serially using .run().
For RBFE calculations of sets of molecules we usually farm out the jobs to a cluster. 

This [notebook](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/02_RBFE/01_setup_rbfe.ipynb) _section 3. Parallelisation - Running the MD simulations_ describes a RBFE setup that will submit all MD simulations on a slurm cluster. The scripts provided with the tutorial can be customised to work with another slurm scheduler or another scheduler. 

I would advise configure a scheduler to manage jobs on a multi-GPU node. This setup may also work for a cloud solution, depending on what route you pursue exactly.

**Comment by lohedges** [comment]
Hi there,

Thanks for your question. Due to the wide range of environments on which BioSImSpace is deployed it is extremely challenging for us to provide support for detecting resources and distributing jobs over these in the most efficient manager. We have specifically made the choice _not_ to attempt to be a workflow manager. While the `.run()` method can be used to run windows in serial or parallel, we wouldn't advise using this if you want to achieve the best performance. Behind the scenes this uses our basic [ProcessRunner](https://biosimspace.openbiosim.org/api/generated/BioSimSpace.Process.ProcessRunner.html#BioSimSpace.Process.ProcessRunner) object. The documentation describes it's limitations.

For large scale simulations we normally use BioSimSpace to set up the inputs for a given engine, then use a workflow manager, or HPC queuing system to distribute these jobs over the available resources. Given your setup, you might want to customise the command-line or configuration options to a specific engine during setup (possible via BioSimSpace), e.g. selecting the number of threads, etc. This is very hard for us to determine without specific knowledge of the system in question, hardware resource, etc.

Cheers.

**Comment by lohedges** [comment]
> To setup the input and store the FE objects would I use the setup_only = True parameter of the Relative() class

This would create the output directories and whatever input files are needed by the specified engines. It doesn't not save/pickle the actual `Relative` object. (No process objects are created in this case.)

> Could I pickle then these objects and create a bash script that will load them into python and call the .run() method? 

Not when using `setup_only=True`, since there wouldn't be any processes to run when unpickling. It might work with `setup_only=False`, but I wouldn't advise running in this way since the resources wouldn't be constrained for the individual processes if running in parallel.

> Something I should have asked more clearly is whether BSS will by default start using the maximum available cores during a single simulation/run() process? Does it have the option to specify how many cores it can use? I'm thinking how gromacs mdrun can use a -nthreads flag to specify the number of 'openmp threads'/cores to use during the run process.

By default we just launch the engine's executable from the command-line using basic settings. Whether all resources are used depends on the type of simulation in question and the particular engine. Some might just hog everything that they can see, others only use a certain number of cores/threads. Since we can't know whether a process is meant to be running in isolation, or as part of a larger workflow in parallel, it's hard for us to specify anything. Within BioSimSpace (or externally) you can always specify precise options for a given engine, e.g. modifying the command-line options, or entries in the configuration file.

By default GROMACS has its own internal logic to try to optimise the process depending on the resources that it can see are available on startup. However, there are a huge number of options that can be tweaked depending on what you want to do. They have a documentation page dedicated to this [here](https://manual.gromacs.org/documentation/current/user-guide/mdrun-performance.html).

For SOMD, you can tell specific processes to use a particular GPU by passing in the `gpu` configuration option. (This is an index into the `CUDA_VISIBLE_DEVICES` environment variable array.) For CPU, it will use all threads that it sees on startup, but this can be limited by specifying, e.g. `OMP_NUM_THREADS`.
