### ISSUE TITLE
[BUG] Water molecule coordinates are setting to (0,0,0) (reposting)

### ISSUE THREAD

**Issue by ale94mleon** [OpenBioSim/biosimspace#148]
I am re-posting issue [427](https://github.com/michellab/BioSimSpace/issues/427) here for future discussion as @lohedges requested.

**Comment by lohedges** [comment]
Thanks for reposting.

> The change in name is not in the gro file but in the topology

Ah, yes, I hadn't checked. It looks like I have forgotten to swap the water topology naming in the gro file within `BioSImSpace.IO.saveMolecule`. Currently it is only done in the top. I'll fix this and also add in an option to preserve the naming if desired. As mentioned in the other thread, we need to change the naming in order to run things with particular engines, or to be able to solvate in the presence of existing waters, but we do want to allow the user to keep the naming if they are just writing a file.

**Comment by lohedges** [comment]
Okay, I've made some updates to allow the user to disable the water topology matching if desired, which it what we want if they are just writing to file.

Looking at the GRO format specification [here](https://manual.gromacs.org/archive/5.0.3/online/gro.html) it is indeed fixed-width. This is why the coordinates were not being parsed correctly. It's hard to add error handling here, since the information is in the file, just in the wrong place.

**Comment by ale94mleon** [comment]
I have another question respect to the preservation of the names after solvate. I know that the water molecules must be continue. But, Could not be added the same kind of parameters also to the solvate?

**Comment by lohedges** [comment]
Yes, this should be possible, but might be a bit tricky. Crystal waters are hard to deal with in general since they aren't always present as separate molecules (see, e.g. #141) and sometimes only appear as oxygen atoms. In order to create a solvent box correctly and for `genion` to see the waters then we do need to convert the formatting to match what GROMACS expects, otherwise we'd need to somehow deal with multiple solvent groups. It should be possible to convert back and the end though, if desired. However, some of the GROMACS functionality for water constraints requires consistent naming to the solvent group. I guess we can just add an option to let the user decide if the naming is changed, after which they can deal with any issues that result from multiple solvent groups.
