### ISSUE TITLE
[BUG] Solvating a system containing an externally merged molecule 

### ISSUE THREAD

**Issue by noahharrison64** [OpenBioSim/biosimspace#188]
**Describe the bug**
Hi,

I'm trying to use BSS with a topology file I have generated myself using PMX. This is a hybrid / merged molecule created after parameterising the following SDFs using BSS: [ejm31.sdf ](https://raw.githubusercontent.com/michellab/BioSimSpaceTutorials/main/04_fep/02_RBFE/inputs/ligands/ejm31.sdf) and [ejm42.sdf](https://raw.githubusercontent.com/michellab/BioSimSpaceTutorials/main/04_fep/02_RBFE/inputs/ligands/ejm42.sdf).

I encounter an issue when trying to solvate the system:
```py
BSSBox = Tuple[List[BSS.Types._length.Length], List[BSS.Types._angle.Angle]]

def create_box(system: SireSystem) -> BSSBox:
    """
    Create a box the size of the system plus 15A padding

    Args:
        system: The SireSystem to create a box for.
    """
    box_min, box_max = system.getAxisAlignedBoundingBox()
    box_size = [(y - x) for x, y in zip(box_min, box_max)]
    padding = 15 * BSS.Units.Length.angstrom
    padding = 30 * BSS.Units.Length.angstrom
    box_length = max(box_size) + 2 * padding
    box, angles = BSS.Box.truncatedOctahedron(box_length.value() * BSS.Units.Length.angstrom)
    return box, angles

def solvate(system: SireSystem, box: BSSBox) -> SireSystem:
    """
    Solvate the system, neutralising any charge

    Args:
        system: The SireSystem to solvate.
        box: The BSSBox to solvate the system into.
    """
    return BSS.Solvent.tip3p(
        system,
        box=box[0],
        angles=box[1],
        work_dir = 'systems_test'
    )

system = BSS.IO.readMolecules(['hybrid_coords.pdb', 'hybrid_top.top'])
box = create_box(system)
solvated = solvate(system, box)

RuntimeError: 'gmx grommp' failed to generate the required output for 'gmx genion'. Perhaps your box is too small?
```

Looking at the grompp.err file it is due to non-zero masses being added to the topology file for the dummy atoms:
The error is linked to an issue I've seen discussed on [here before](https://github.com/michellab/BioSimSpace/issues/31), although I can't see a fix that would help me. 
```
ERROR 1 [file solvated.top, line 446]:
  virtual site HV (Res MOL-1) has non-zero mass 1.008 (state A) / 1.008
  (state B)
       Check your topology.
```

If I set the masses of the dummy atoms to 0 in the hybrid_top.top file and then re-run the sequence of commands defined in the README.txt file then the process works as expected. 

I can see that in my topology file (hybrid_top.top) I have the dummy atom masses in the [atoms] directive set to 1.0008 and so it makes sense that BSS writes the masses as non-zero values. However, I have no issues running this hybrid_top.top file directly via gromacs (I have to do a little modification to the BSS-created top file to make it gromacs ready, i.e. adding the necessary include forcefield lines, I have attached 'mod_hybrid_top.top' which contains these modifications). 

```
gmx editconf -f hybrid_coords.pdb -o box.pdb -d 1 -bt dodecahedron
gmx solvate -cs spc216.gro -cp box.pdb -o solvated.pdb -p mod_hybrid_top.top
gmx grompp -f ions.mdp -c solvated.pdb -p mod_hybrid_top.top -o ions.tpr 
```

Any advice on how to handle this situation would be greatly appreciated. It is entirely plausible that the issue I'm facing is entirely down to the hybrid_top.top file created by PMX being erroneous - perhaps the masses in the lambda A and the lambda B state should be different, although I've run plenty of FEP simulations with this style of top file and encountered no errors before.

I am looking to implement the BSS.Align.merge functionality and can maybe stop using PMX (although would like to check that they're creating similar hybrid molecules) but I would like to try and figure this out if possible.

**Input files**
hybrid_top.top, hybrid_coords.pdb and mod_hybrid_top.top can be found in this [GDrive folder](https://drive.google.com/drive/folders/13dasW_GOQM0tVZkBHnKeexND7StlUqPb?usp=share_link)

**(please complete the following information):**
 - OS: Linux
 - Version of Python: 3.9
 - Version of BioSimSpace: 2023_4_0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by lohedges** [comment]
Hi there.

> ...although I've run plenty of FEP simulations with this style of top file and encountered no errors before

Yes, there will be no issues running FEP with GROMACS with such a topology. The issue is when you try to use GROMACS for non-FEP stuff, where it breaks. As you've found, we've worked around this in BioSimSpace by modifying the topology file, which allows us to use tools such as `genion`, or run regular dynamics for one of the end states. However, this relies on the molecule being flagged as being perturbable by having an `is_perturbable` property, which is then picked up by our GROMACS parser. It's not possible to tag your molecule with this, since it doesn't match the expected merged molecule formatting, i.e. it only contains a single end state. (We currently can't read in GROMACS hybrid topologies directly, although it is possible using a script such as the one in [this](https://github.com/michellab/BioSimSpace/issues/234) thread.)

> I am looking to implement the BSS.Align.merge functionality and can maybe stop using PMX (although would like to check that they're creating similar hybrid molecules) but I would like to try and figure this out if possible.

I think the best way to check this would be with single-point calculations. This can be done internally using Sire, which we do for the existing merged systems that we support. You could also set up the hybrid topologies using PMX and BSS, then use GROMACS to calculate single-point energies at different values of lambda to make sure they agree.

**Comment by noahharrison64** [comment]
Thanks for the reply @lohedges 

I understand the issue at hand. Is it possible to write BSS merged molecules to gromacs-ready topology files, which can then be run through GMX via CLI, transitioning from lambda 0 to lambda 1? Or must they be simulated using BSS as a wrapper around GMX?

**Comment by lohedges** [comment]
Both are possible. Once you have created a merged molecule/system with BioSimSpace you can either just write out the topology and run manually, or use BioSimSpace to set up GROMACS and run things for you, or just set things up with BioSimSpace, copy the GROMACS input files elsewhere and run manually.

**Comment by noahharrison64** [comment]
Okay thanks for the info!

**Comment by noahharrison64** [comment]
Sorry I think I slightly misunderstood your initial reply. I thought using the BSS.Align.Merge functionality would allow me to create hybrid files that were compatible with BSS. Having tested this (and it failing to work due to the same issue as before) I think I understand now that the issue with reading in hybrid topology files is because of the gromacs format in general, rather than me creating this hybrid topology using an external program. So I now think I have two options?

*  Save the merged molecule in a specific format, such as amber, as oppose to using gro87 / grotop. Reading in a compatible format BSS will add the is_perturbable property to the molecule
*  Or parse the merged system directly to the Solvate function without writing to disk?

**Comment by lohedges** [comment]
> I thought using the BSS.Align.Merge functionality would allow me to create gromacs hybrid files that were compatible with BSS.

Yes, but only for the purposes of running an FEP simulation with GROMACS. Since we can't read the hybrid topology back, it won't work for further GROMACS operations, e.g. solvation, as you are finding here.

> Save the merged molecule in a specific format, such as amber, as oppose to using gro87 / grotop. Reading in a compatible format BSS will add the is_perturbable property to the molecule

For text format, we have `BioSimSpace.IO.savePerturbableSystem`, which will save the two end states to AMBER format coordinate and topology files. Using `BioSimSpace.IO.readPerturbableSystem` you can then read these back in. There are tests to make sure that the round-trip is correct, i.e. no information is lost. This could be updated to work with GROMACS files too, but we chose AMBER since the topology file is always self-contained. You can also stream the system to binary format using `BioSimSpace.Stream.save`, which will is what we tend to use within a workflow.

> Or parse the merged system directly to the Solvate function without writing to disk?

If you've created a merged system within BioSImSpace then solvation should work, since the workarounds from the other thread will be applied when writing to GROMACS format.

>  I think I understand now that the issue with reading in hybrid topology files is because of the gromacs format in general, rather than me creating this hybrid topology using an external program. So I now think I have two options:

I'm not sure. We never got round to adding a reader for GROMACS hybrid topologies, but it's certainly something that can be done. I just they are only intended to be used for FEP simulations, so people don't typically encounter these issues. (Perhaps people solvate the lambda = 0 state, then create the hybrid topology?)

**Comment by noahharrison64** [comment]
Okay that's great, thanks for all the information its been super helpful @lohedges!
