### ISSUE TITLE
[BUG] GROMACS MD Simulation resulting in unexpected pressure scaling warning 

### ISSUE THREAD

**Issue by portmanrk** [OpenBioSim/biosimspace#195]
**Describe the bug**
When using BSS.Protocol.Production() to run an MD simulation of an RNA:smallmolecule system using GROMACS, the system output file returns a pressure warning:
![Pressure warning](https://github.com/OpenBioSim/biosimspace/assets/145602879/f98d214a-ed4b-4b08-9538-adca3d6be2e2)
Visually this causes the RNA:smallmolecule system to break apart and bubbles to form in the solvent. 

**To Reproduce**

```
import BioSimSpace as BSS

print("Loading system...")
system= BSS.IO.readMolecules("../equilib_minim/prep/protein/mol_sys_equil_solv.*")
protocol=BSS.Protocol.Production(runtime= 100 * BSS.Units.Time.nanosecond, report_interval=10_000)
process = BSS.Process.Gromacs(system, protocol, work_dir="output_gmx_3")
process.start()
process.wait()
```

**Expected behavior**
Simulations of the same RNA:smallmolecule system using Amber and OpenMM did not result in this issue. In these cases no bubbles formed, the system stayed together and no pressure warnings appeared in the output file.
**Input files**
[Input files.zip](https://github.com/OpenBioSim/biosimspace/files/13249889/Input.files.zip)

**(please complete the following information):**
 - OS: Ubuntu
 - Version of Python: 3.10.12
 - Version of BioSimSpace: 2023.4.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by lohedges** [comment]
Hi there,

Thanks for posting. Could you please let us know what version of GROMACS you are using? I'm running locally using `2023.2` from `conda-forge` and I'm not seeing any issues. (No warnings after 3000 steps.) Also, are you running on GPU?

Have you tried doing a re-minimisation with GROMACS prior to running? Since you are using text based input files it's possible that there is some precision loss in the coordinates that is causing an instability. This might be more of a problem if you are running on GPU, where it might only be using single precision.

If you still have issues I'll try to match the GROMACS version to see if some setting isn't working well for the version that you are using.

Cheers.

**Comment by portmanrk** [comment]
Hi,

Thank you for your reply. After further investigation on different machines it has worked without this issue. Hence, it was likely a problem with GROMACS and not BioSimSpace. I will now close the issue.

**Comment by lohedges** [comment]
No problem at all. Thanks for confirming.
