### ISSUE TITLE
_check_box_size Fails for rhombicDodecahedronHexagon Box with Reasonable Padding

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#211]
**Describe the bug**

Previously, [`_check_box_size`](https://github.com/OpenBioSim/biosimspace/blob/92999adb4674863785cd850da80c3022f832c544/python/BioSimSpace/Solvent/_solvent.py#L1455) passed when using [this setup code](https://github.com/fjclark/EnsEquil/blob/952ccdf69d3f1fb759f1e6f25ebcc6d755e1ebaf/EnsEquil/run/system_prep.py#L142C9-L142C9). `mol_box` inside `_check_box_size` was:
```
77.9578
59.1235
62.4624
```
and `box` was
```
84.1914
72.9136
84.1914
```
However, following [changes in sire](https://github.com/OpenBioSim/sire/issues/49), now the box lengths are reordered:
```
72.9136
84.1914
84.1914
```
which causes the first comparison in `_check_box_size` to fail.

**To Reproduce**
Use [this code](https://github.com/fjclark/EnsEquil/blob/952ccdf69d3f1fb759f1e6f25ebcc6d755e1ebaf/EnsEquil/run/system_prep.py#L140) to solvate `bound_param.prm7/rst7` [here](https://github.com/fjclark/EnsEquil/tree/main/EnsEquil/data/example_run_dir/input).

 - OS: Ubuntu 20.04
 - Version of Python: 3.11
 - Version of BioSimSpace/Sire: 2023.5.0.dev
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

Thanks.

**Comment by lohedges** [comment]
The reordering is an expected change to our reduction code, but it's surprising that this causes the check to fail since the volume should be the same. It implies that the box check isn't working (or appropriate) for triclinic spaces. I'll debug on Monday.

**Comment by lohedges** [comment]
I see the problem. The fixed reduction has the shortest box length aligned with the x-axis, which is what OpenMM needs. We'll need to update the logic to generate an appropriate box size from the AABox by making sure this is true, or rotating they molecule accordingly.

**Comment by lohedges** [comment]
I've taken another look at this and the issue is that you are using the _dry_ system (no waters) to compute the optimal box size, but passing the full system (non water plus water) to the solvation function, so the AABBox is different, i.e.:

```python
import BioSimSpace as BSS

In [2]: s = BSS.IO.readMolecules("*7")

In [3]: s
Out[3]: <BioSimSpace.System: nMolecules=7>

In [4]: non_waters = [mol for mol in s if mol.nAtoms() != 3]
   ...: dry_system = BSS._SireWrappers._system.System(non_waters)
   ...: box_min, box_max = dry_system.getAxisAlignedBoundingBox()

In [5]: box_min
Out[5]: [6.2533 A, 13.4997 A, 31.8905 A]

In [6]: box_max
Out[6]: [59.7580 A, 67.6912 A, 83.7451 A]

In [7]: box_min2, box_max2 = s.getAxisAlignedBoundingBox()

In [8]: box_min2
Out[8]: [6.2533 A, 13.4997 A, 21.2827 A]

In [9]: box_max2
Out[9]: [84.2111 A, 72.6233 A, 83.7451 A]
```

As you can see, while the AABBox minima are the same, the x and y components of `box_max2` are _larger_ than `box_max`. Indeed, if I just pass `dry_system` to the solvate function using your existing values for `box` and `angles`, then everything works as expected. The same is true if I pass `parameterised_system` based on the _new_ `box` and `angles` generated from `box_min2` and `box_max2` above.

**Comment by fjclark** [comment]
Thanks very much and apologies that this was my mistake. 

Given that I would like to calculate the bounding box based on the protein/ligand without crystallographic waters, but would like to solvate the system with crystallographic waters present, would it make sense to expose `check_box` to `solvate`? Happy to make these changes and PR if so. Thanks

**Comment by lohedges** [comment]
Yes, that could be a useful function to expose so that the user can tune things before solvating. At present it's a private function with Pythonic naming. If exposed, it should follow the usual BioSimSpace public naming convention, e.g. `checkBoxSize`.

> Given that I would like to calculate the bounding box based on the protein/ligand without crystallographic waters, but would like to solvate the system with crystallographic waters present...

Sorry, I'm a bit confused. If you don't include the waters in the bounding box calculation then the bounds for your solvation box might be too small, right? Is there a reason why you want to exclude them during the AABox calculation?

**Comment by fjclark** [comment]
Sorry, I was confused. Yes, the waters must be included in the bounding box calculation. I wanted to exclude them during the AABox calculation so that I didn't end up with a massive box because of a crystallographic water far from the protein, and was assuming that all waters would lie within the padding I added to the dry bounding box. I can see now that I just need to search for waters too far from the protein and exclude them. Thanks.
