### ISSUE TITLE
Add a flag to BSS.Align.decouple to only change the sire property when using this for SOMD

### ISSUE THREAD

**Issue by xiki-tempula** [OpenBioSim/biosimspace#252]
@fjclark Do you mind add a flag to BSS.Align.decouple to only change the sire property when the SOMD flag is on?
I'm working on some Gromacs work that involves changing some sire property of decouple molecule and it is unfortunate that the changes that I want to make is imcompactible the current SOMD flags is in compatible with my work.
Namely 

1. The `LJ1` will be having the same sigma and 0 epsilon
2. The `element1` will be the same element instead of 0
3. The `ambertype1` cannot be du for my case, but automatically generated by Sire

So I think it will be the best if there is a flag to only make these changes for SOMD and allows both of us to work on this.

**Comment by lohedges** [comment]
This could potentially be done in the `_to_pert_file` method of `BioSimSpace.Process.Somd`. This applies some modifications to the terms in order to write the SOMD perturbation file, along with updating some of the properties in the molecule. This way the molecule would only be modified inside of the SOMD process during setup, leaving the behaviour of the decouple function unchanged regardless of the engine.

**Comment by xiki-tempula** [comment]
@lohedges This would be ideal.

**Comment by fjclark** [comment]
@xiki-tempula of course. I'll try and implement Lester's suggestion this afternoon.

**Comment by xiki-tempula** [comment]
@fjclark  Thank you very much.
