### ISSUE TITLE
Question: does the RBFE ATM method analysis work also for ABFE?

### ISSUE THREAD

**Issue by hjuinj** [OpenBioSim/biosimspace#372]
Hi, very exciting work reported in https://www.openbiosim.org/biosimspace-diaries-alchemical-transfer-method/ today, well done @mb2055 et al. !

I have a quick question about the analysis code, in the original UWHAM analysis from Gallicchio Lab written in R, the [ABFE](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/ABFE/fkbp/scripts/uwham_analysis.R) and [RBFE](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/RBFE/temoa-g1-g4/uwham_analysis.R) analysis code is basically the same, differing in a single sign change. May I ask, with the python ported version here showcased for RBFE in the above post, whether the UWHAM version or the MBAR version can also be directly applied to ABFE trajectories as well?

**Comment by mb2055** [comment]
Currently we only support RBFE across the entire pipeline, so the analysis will only work for RBFE data (at least that is all its been tested on).
As you say the difference in analysis between the two is minor, so in principle we could support analysis of ABFE data, but since we can only _run_ RBFE calculations any ABFE analysis would be difficult to test.

**Comment by hjuinj** [comment]
thanks, is ATM ABFE support coming?
