### ISSUE TITLE
[BUG] Adding a cofactor

### ISSUE THREAD

**Issue by velocirraptor23** [OpenBioSim/biosimspace#67]
Hi,

I have tried to pull all togheter a protein a ligand a and B and a cofactor. I managed to run the parametrization of the four components. Also before to merge all togheter I create the mapping between the two ligands (A and B), then I merged then after that using the next line complx = merged + RNMT + cofactor.

The I tried to minimize the system but it fails to do that. The error is: RuntimeError: 'gmx genion' failed to add ions! Perhaps your box is too small?. I increase the size of the box, but it fails no matter the size. When I merge only protein and merged ligands, it works well. 

Thanks a lot

Cesar

**Comment by jmichel80** [comment]
Can you submit a minimal example script and input files to allow others to reproduce the issue you are reporting ?

**Comment by lohedges** [comment]
Hi @velocirraptor23. Yes, please submit a minimal example so that we can debug.

> The I tried to minimize the system but it fails to do that. The error is: RuntimeError: 'gmx genion' failed to add ions! 

I assume you mean _solvate_, not minimise?

Note that the "Perhaps your box is too small?" suggestion is currently a catch-all for `genion` failure since it's the most common (and likely) issue. If you want to see the full log files then please use the `work_dir` option to specify a local working directory so that you can examine the files after failure. This includes _all_ of the intermediate files, along with a `README.txt` stating the _exact_ sequence of commands that were run so that you can reproduce. For example:

```python
import BioSimSpace as BSS

mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

solvated = BSS.Solvent.tip3p(mol, box=3*[5*BSS.Units.Length.nanometer], work_dir="sol_test")
```

Looking in the `sol_test` directory you should see something like:

```
ls -l sol_test
total 3.1M
-rw-r--r-- 1 lester lester  341 May 16 18:40 box.gro
-rw-r--r-- 1 lester lester  454 May 16 18:40 editconf.err
-rw-r--r-- 1 lester lester  317 May 16 18:40 editconf.out
-rw-r--r-- 1 lester lester  617 May 16 18:40 genion.err
-rw-r--r-- 1 lester lester    0 May 16 18:40 genion.out
-rw-r--r-- 1 lester lester  852 May 16 18:40 grommp.err
-rw-r--r-- 1 lester lester  483 May 16 18:40 grommp.out
-rw-r--r-- 1 lester lester  326 May 16 18:40 input.gro
-rw-r--r-- 1 lester lester  233 May 16 18:40 ions.mdp
-rw-r--r-- 1 lester lester  11K May 16 18:40 ions.out.mdp
-rw-r--r-- 1 lester lester 290K May 16 18:40 ions.tpr
-rw-r--r-- 1 lester lester 535K May 16 18:40 output.gro
-rw-r--r-- 1 lester lester  628 May 16 18:40 README.txt
-rw-r--r-- 1 lester lester 642K May 16 18:40 solvated.gro
-rw-r--r-- 1 lester lester 535K May 16 18:40 solvated_ions.gro
-rw-r--r-- 1 lester lester 2.6K May 16 18:40 solvated.top
-rw-r--r-- 1 lester lester 1.1K May 16 18:40 solvate.err
-rw-r--r-- 1 lester lester  862 May 16 18:40 solvate.out
-rw-r--r-- 1 lester lester 535K May 16 18:40 water.gro
-rw-r--r-- 1 lester lester 535K May 16 18:40 water_ions.gro
-rw-r--r-- 1 lester lester  300 May 16 18:40 water_ions.top
```

To see the `genion` errors, look at `genion.err`. The `README.txt` will tell you what was run, e.g.:

```
cat sol_test/README.txt

# gmx editconf was run with the following command:
/usr/local/gromacs/bin/gmx editconf -f input.gro -bt triclinic -box 3.000000 3.000000 3.000000 -angles 90.000000 90.000000 90.000000 -noc -o box.gro

# gmx solvate was run with the following command:
/usr/local/gromacs/bin/gmx solvate -cs spc216 -cp box.gro -o output.gro

# gmx grompp was run with the following command:
/usr/local/gromacs/bin/gmx grompp -f ions.mdp -po ions.out.mdp -c solvated.gro -p solvated.top -o ions.tpr

# gmx genion was run with the following command:
/usr/local/gromacs/bin/gmx genion -s ions.tpr -o solvated_ions.gro -p solvated.top -neutral -np 0
```

Cheers.

**Comment by lohedges** [comment]
Hi @velocirraptor23, is there any update on this? I'd be interested to debug since we don't have special handling for additional ions or cofactors in our solvation routine. (We do handle the presence of existing water molecules.)

**Comment by velocirraptor23** [comment]
Dear all, 

Getting back to you has been complicated with a proper answer; I will reply ASAP. Thanks both for following this issue.

**Comment by velocirraptor23** [comment]
Hi again, 

I'll explain what I am trying to do with the code. I am interested in integrating a cofactor into my system. Three components are ligand + cofactor + protein. The perturbation is applied to the ligand. Yes, the error is coming during solvation. I attached the error file in case you want to have a look. I suspect it is how I merged the system, or it could be because the cofactor has a negative charge (-3).
I am following the next steps
#Read inputs
protein = BSS.IO.readMolecules("Coversion2_B/inputs/protein.pdb")[0]
A = BSS.IO.readMolecules("Coversion2_B/inputs/1870799_F.pdb")[0]
B = BSS.IO.readMolecules("Coversion2_B/inputs/1870799_FB.pdb")[0]
cofactor = BSS.IO.readMolecules("Coversion2_B/inputs/SAH.pdb")[0]

#Parametrize components
protein = BSS.Parameters.ff14SB(RNMT,water_model="tip3p").getMolecule()
cofactor = BSS.Parameters.gaff2(cofactor).getMolecule()
A = BSS.Parameters.gaff2(A).getMolecule()
B = BSS.Parameters.gaff2(B).getMolecule()

#Mapping ligands
mapping = BSS.Align.matchAtoms(A, B)
inv_mapping = {v: k for k, v in mapping.items()}
B_aligned = BSS.Align.rmsdAlign(B, A, inv_mapping)
merged = BSS.Align.merge(A, B_aligned, mapping)

#Merge components
complx = merged + protein + cofactor

#Solvate and create inputs for the free leg
merged_sol_smaller = BSS.Solvent.tip3p(molecule=merged, work_dir="Coversion2_B", box=3*[30*BSS.Units.Length.angstrom])
protocol = BSS.Protocol.FreeEnergy(runtime=8*BSS.Units.Time.nanosecond, num_lam=12)
fep_free = BSS.FreeEnergy.Relative(merged_sol_smaller, protocol, work_dir="Coversion2_B/free")

#Solvate the complex (error comes here)
complex_sol = BSS.Solvent.tip3p(molecule=complx, box=3*[80*BSS.Units.Length.angstrom], work_dir="sol_test")

#Relaxation of the system and creation of the bound leg files
minimised = BSS.Process.Amber(complex_sol, BSS.Protocol.Minimisation()).start().getSystem(block=True)
equilibrated = BSS.Process.Amber(minimised, BSS.Protocol.Equilibration()).start().getSystem(block=True)
protocol = BSS.Protocol.FreeEnergy(runtime=4*BSS.Units.Time.nanosecond, num_lam=12)
fep_bound = BSS.FreeEnergy.Relative(equilibrated, protocol, work_dir="Coversion2_B/bound")

**Comment by velocirraptor23** [comment]
This is what the error file says.

                :-) GROMACS - gmx genion, 2022.4-conda_forge (-:

Executable:   /cluster/ddu/cmmartinez001/miniconda3/envs/openbiosim-dev/bin.AVX2_256/gmx
Data prefix:  /cluster/ddu/cmmartinez001/miniconda3/envs/openbiosim-dev
Working dir:  /cluster/ddu/cmmartinez001/Projects/RNMT/Openbiosim/sol_test
Command line:
  gmx genion -s ions.tpr -o solvated_ions.gro -p solvated.top -neutral -nn 4

Reading file ions.tpr, VERSION 2022.4-conda_forge (single precision)
Reading file ions.tpr, VERSION 2022.4-conda_forge (single precision)
Group     0 (         System) has 50998 elements
Group     1 (          Other) has    95 elements
Group     2 (            LIG) has    49 elements
Group     3 (            SAH) has    46 elements
Group     4 (        Protein) has  4544 elements
Group     5 (      Protein-H) has  2276 elements
Group     6 (        C-alpha) has   275 elements
Group     7 (       Backbone) has   828 elements
Group     8 (      MainChain) has  1104 elements
Group     9 (   MainChain+Cb) has  1364 elements
Group    10 (    MainChain+H) has  1380 elements
Group    11 (      SideChain) has  3164 elements
Group    12 (    SideChain-H) has  1172 elements
Group    13 (    Prot-Masses) has  4544 elements
Group    14 (    non-Protein) has 46454 elements
Group    15 (          Water) has 46359 elements
Group    16 (            SOL) has 46359 elements
Group    17 (      non-Water) has  4639 elements
Select a group: 
-------------------------------------------------------
Program:     gmx genion, version 2022.4-conda_forge
Source file: src/gromacs/gmxpreprocess/genion.cpp (line 603)

Fatal error:
The solvent group SOL is not continuous: index[36]=4629, index[37]=4676

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------

**Comment by lohedges** [comment]
Thanks, this is really helpful. The error in the `genion.err` file is thankfully quite clear:

```
Fatal error:
The solvent group SOL is not continuous: index[36]=4629, index[37]=4676
```

There is logic in the code to deal with existing water molecules in the system to make sure that they are combined with ones added by `gmx solvate` to create a contiguous block before passing to `gmx genion`. Clearly something is going wrong here when the co-factor is present. If you are able to share the inputs to your script, then that would be great. I imagine that there's nothing particular special about the system in order to trigger this error, so I might even be able to create a minimal example to reproduce locally.

**Comment by velocirraptor23** [comment]
You are entirely right. I deleted the waters I wanted to conserve in the binding site. And for the parametrisation, I used
protein = BSS.Parameters.ff14SB(protein).getMolecule()
The solvation was made properly. But then it failed in the last command line
fep_bound = BSS.FreeEnergy.Relative(equilibrated, protocol, work_dir="Coversion2_B/bound
The jupyter ntb shows this
TypeError: 'system' must be of type 'BioSimSpace._SireWrappers.System'

If I don't take the cofactor, and I take the waters from the binding site, the solvation works well too. I just can't have both water and cofactor at the same time.

The first conclusion is that if I use waters in the binding site along with the cofactor, the keyword water model clashes somehow with that.
About the latest error, I don't know why it sometimes happens to me, but then when I reboot the Jupyter Notebook, it usually works well again, This time didn't happen, it seems a consistent error and it happens in both cases when I have waters or cofactor.

I deeply feel sorry but I can't share the protein structure or ligands; they will be published soon, but there is an agreement not to make this data public. However, I can look at another potential target (I got some idea of which one can be a good example) and see if I can reproduce this error.

Is there any other way to consider waters during the parametrisation to avoid the solvation error? For the latest error, not sure what exactly means that.

Thanks a lot for your guidance.

**Comment by lohedges** [comment]
No problem, let me know if you find something shareable that reproduces the issue. That's useful to know that it _does_ work with crystal waters or the co-factor independently, but not together. I think we must have messed something up when creating the composite system for `gmx genion`.

```python
fep_bound = BSS.FreeEnergy.Relative(equilibrated, protocol, work_dir="Coversion2_B/bound
The jupyter ntb shows this
TypeError: 'system' must be of type 'BioSimSpace._SireWrappers.System'
```

For this error, are you checking that your equilibration process was run successfully and the equilibrated system that was returned is not `None`. Because you are running interactively, you might have forgotten to _wait_ for the process to finish before getting the system.

```python
# This is your equilbration process.

# Start it.
process.start()

# Wait for it to finish.
process.wait()

# Was there an error?
if process.isError():
    raise Exception("The equilibration process failed!")
    
# Get the final system.
equilibrated = process.getSystem()

# Did we get back a system?
is system is None:
    raise Exception("No system was returned?")
```

We only don't raise an exception if there is no system since it's possible that there won't be one due to the protocol in question, the particular settings, if any restart or trajectory frames have been written, etc. I am considering always raising an exception anyway, or simply giving a warning if nothing is returned.

**Comment by lohedges** [comment]
The following gives and example where I  solvated around a system made of two molecules and two existing waters. Here the solvation works okay.

```python
In [1]: import BioSimSpace as BSS

INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

In [2]: s = BSS.IO.readMolecules(BSS.IO.expand(BSS.tutorialUrl(), ["ala.top", "ala.crd"]))
Downloading from 'https://biosimspace.openbiosim.org/m/ala.top'...
Unzipping '/tmp/tmpmykro_3g/ala.top.bz2'...
Downloading from 'https://biosimspace.openbiosim.org/m/ala.crd'...
Unzipping '/tmp/tmpmykro_3g/ala.crd.bz2'...

In [3]: m = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [4]: system = (s[0] + s[1:3] + m).toSystem()

In [5]: for mol in system:
   ...:     print(mol)
   ...:
<BioSimSpace.Molecule: number=25, nAtoms=22, nResidues=3>
<BioSimSpace.Molecule: number=108, nAtoms=3, nResidues=1>
<BioSimSpace.Molecule: number=138, nAtoms=3, nResidues=1>
<BioSimSpace.Molecule: number=633, nAtoms=5, nResidues=1>

In [6]: solvated = BSS.Solvent.tip3p(system, box=3*[4*BSS.Units.Length.nanometer])

In [7]: for mol in solvated[0:4]:
   ...:     print(mol)
   ...:
<BioSimSpace.Molecule: number=25, nAtoms=22, nResidues=3>
<BioSimSpace.Molecule: number=633, nAtoms=5, nResidues=1>
<BioSimSpace.Molecule: number=108, nAtoms=3, nResidues=1>
<BioSimSpace.Molecule: number=138, nAtoms=3, nResidues=1>
 ```
 
 This works for any ordering of the molecules in `system` that I've tried. Note that in the solvated system the water molecules are placed at the end, i.e. atom number `633` has gone from index `3` in `system` to index `1` in solvated. This is because of the need to make a contiguous block of water molecules for `gmx genion`. I'm interested to know why this logic is failing with your co-factor. We just use our built-in search functionality to find the water molecules and move them, which wouldn't detect the co-factor. All I can think is that it is part of a residue named `SOL` for some reason?

**Comment by velocirraptor23** [comment]
Hi,

I think I might find the reason it failed. As you said, it is the order we make the complex. I just changed the order for making it.

Before fails like this:

complx = merged + protein + cofactor

But works like this including waters

complx = cofactor + merged + protein or complx = merged + cofactor + protein

Working now in solving the second issue.

**Comment by lohedges** [comment]
Okay, interesting. It should work in any order though. Are the waters actually embedded in the protein, i.e. part of the structure, rather than being separate molecules?
